GestionaleCorriere/Controllers/DataOdiernaController.cs
using GestionaleCorriere.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Web.Mvc;

namespace GestionaleCorriere.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DataOdiernaController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetDataOdierna1()
        {
            var model = new List<Spedizione>();
            return View(model);
        }

        public List<Spedizione> Consegna = new List<Spedizione>();
        public string ConnectionString = ConfigurationManager.ConnectionStrings["Gestionale"].ConnectionString;
        public string Query = "SELECT * FROM Spedizione";

        public JsonResult GetDataOdierna()
        {
            using (SqlConnection con = new SqlConnection(ConnectionString))
            {
                using (SqlCommand cmd = new SqlCommand(Query, con))
                {
                    con.Open();
                    SqlDataReader reader = cmd.ExecuteReader();
                    while (reader.Read())
                    {
                        var spedizione = new Spedizione
                        {
                            idSpedizione = Convert.ToInt32(reader["idSpedizione"]),
                            FK_idCliente = Convert.ToInt32(reader["FK_idCliente"]),
                            codTracciamento = reader["codTracciamento"].ToString(),
                            dataSpedizione = Convert.ToDateTime(reader["dataSpedizione"]),
                            pesoSpedizione = Convert.ToDecimal(reader["pesoSpedizione"]),
                            cittaDestinazione = reader["cittaDestinazione"].ToString(),
                            nominativoDestinatario = reader["nominativoDestinatario"].ToString(),
                            costoSpedizione = Convert.ToDecimal(reader["costoSpedizione"]),
                            dataConsegna = Convert.ToDateTime(reader["dataConsegna"])
                        };

                        Consegna.Add(spedizione);
                    }
                    con.Close();
                }
            }
            return Json(Consegna, JsonRequestBehavior.AllowGet);
        }
    }
}

GestionaleCorriere/Controllers/UtenteController.cs
using GestionaleCorriere.Models;
using System;
using System.Configuration;
using System.Data.SqlClient;
using System.Web.Mvc;
using System.Web.Security;

namespace GestionaleCorriere.Controllers
{
    public class UtenteController : Controller
    {
        // GET: Utente
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Utenti utente)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    string connectionString = ConfigurationManager.ConnectionStrings["Gestionale"].ConnectionString;
                    using (SqlConnection connection = new SqlConnection(connectionString))
                    {
                        string query = "SELECT * FROM Utenti WHERE Username = @Username AND Password = @Password";
                        using (SqlCommand command = new SqlCommand(query, connection))
                        {
                            connection.Open();

                            command.Parameters.AddWithValue("@Username", utente.Username);
                            command.Parameters.AddWithValue("@Password", utente.Password);

                            using (SqlDataReader reader = command.ExecuteReader())
                            {
                                if (reader.HasRows)
                                {
                                    FormsAuthentication.SetAuthCookie(utente.Username, false);
                                    return RedirectToAction("Index", "Home");
                                }
                                else
                                {
                                    ViewBag.AuthError = "Autenticazione non riuscita";
                                    return View();
                                }
                            }
                        }
                    }
                }
                catch (SqlException ex)
                {
                    System.Diagnostics.Debug.WriteLine($"Errore SQL: {ex.Message}");
                    return View("Error"); // You can create a specific view for SQL errors
                }
                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine($"Errore generale: {ex.Message}");
                    return View("Error");
                }
            }
            else
            {
                return View("Create", utente);
            }
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

GestionaleCorriere/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Applicazione ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-danger">
        <div class="container">

            @Html.ActionLink("Caronte Trasporti", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Attiva/Disattiva spostamento" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Informazioni", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Accedi", "Login", "Utente", new { area = "" }, new { @class = "nav-link ms-5 me-5" })</li>
                    }

                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Inserisci Cliente", "Create", "Cliente", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Inserisci Spedizione", "Spedizione", "Spedizione", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Spedizioni Odierne", "GetDataOdierna1", "DataOdierna", new { area = "" }, new { @class = "nav-link", @id = "btnSpedizioni" })</li>
                    }

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a href="@Url.Action("Logout", "Utente")" class="nav-link ms-5">Logout</a></li>
                    }
                </ul>
            </div>

        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Caronte Trasporti</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <script type="text/javascript">
        $('#btnSpedizioni').click(function () {
            $.ajax({
                url: '/GetDataOdierna1/DataOdierna',
                type: 'GET',
                success: function (result) {
                    $('#btnSpedizioni').html(result);
                }
            });
        });
    </script>

    @RenderSection("scripts", required: false)
</body>
</html>